### ISSUE TITLE
what license is this?

### ISSUE THREAD

**Issue by hloeffler** [toikarin/sgf#1]
Hello,
what license is this?

Best,
Hauke

**Comment by toikarin-arm** [comment]
I haven't licensed this with any particular license. Do you have some requirements or why are you asking? I would not mind licensing this with something like MIT.

**Comment by hloeffler** [comment]
thanks
i want to use :)
MIT or BSD is just fine

**Comment by toikarin** [comment]
(Replying with my personal account)
I haven't licensed this with any particular license. Do you have some requirements or why are you asking? I would not mind licensing this with something like MIT.

**Comment by toikarin** [comment]
Added LICENSE

**Comment by hloeffler** [comment]
thanks
